from PyQt6.QtWidgets import QWidget, QFormLayout, QSpinBox, QDoubleSpinBox, QCheckBox, QComboBox, QLabel, QGroupBox, QPushButton, QHBoxLayout, QSpacerItem, QSizePolicy, QLineEdit

class ServerPage(QWidget):
    def __init__(self):
        super().__init__()
        layout = QFormLayout(self)
        # Model Type
        self.model_type = QComboBox()
        self.model_type.addItems(["cpsam", "cyto2", "cyto3", "custom"])
        self.model_type.setCurrentText("cpsam")
        model_label = QLabel("Model Type")
        model_label.setToolTip("Type of the Cellpose model, e.g., 'cyto2', 'cyto3'. Defaults to 'cpsam'.")
        layout.addRow(model_label, self.model_type)
        # Pretrained model path (for custom model)
        self.pretrained_model_row_widget = QWidget()
        self.pretrained_model_row_layout = QHBoxLayout(self.pretrained_model_row_widget)
        self.pretrained_model_row_layout.setContentsMargins(0, 0, 0, 0)
        pretrained_label = QLabel("Pretrained Model Path")
        pretrained_label.setToolTip("Path to a custom pretrained model. Only used if model type is 'custom'.")
        self.pretrained_model_input = QLineEdit()
        self.pretrained_model_input.setPlaceholderText("/path/to/model.pth")
        self.pretrained_model_input.setMinimumWidth(505)
        self.pretrained_model_row_layout.addWidget(pretrained_label)
        self.pretrained_model_row_layout.addSpacerItem(QSpacerItem(5, 0, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum))
        self.pretrained_model_row_layout.addWidget(self.pretrained_model_input)
        self.pretrained_model_row_layout.addStretch(1)
        layout.addRow(self.pretrained_model_row_widget)
        self.pretrained_model_row_widget.hide()

        # Denoise and Restore Type (dynamic row)
        self.denoise_row_widget = QWidget()
        self.denoise_row_layout = QHBoxLayout(self.denoise_row_widget)
        self.denoise_row_layout.setContentsMargins(0, 0, 0, 0)
        self.do_denoise = QCheckBox()
        self.do_denoise.setChecked(True)
        denoise_label = QLabel("Denoise")
        denoise_label.setToolTip("If True, will use the denoising model. Defaults to True. Deprecated in cellpose>=4.0, parameter will be ignored.")
        self.denoise_row_layout.addWidget(denoise_label)
        self.denoise_row_layout.addSpacerItem(QSpacerItem(112, 0, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum))
        self.denoise_row_layout.addWidget(self.do_denoise)
        self.denoise_row_layout.addSpacerItem(QSpacerItem(80, 0, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum))
        self.restore_type = QComboBox()
        self.restore_type.addItems(["denoise_cyto3", "denoise_cyto2"])
        self.restore_type.setCurrentText("denoise_cyto3")
        restore_label = QLabel("Restore Type")
        restore_label.setToolTip("Type of restoration for the Cellpose model, e.g., 'denoise_cyto2', 'denoise_cyto3'. Defaults to 'denoise_cyto3'. Deprecated in cellpose>=4.0, parameter will be ignored.")
        self.denoise_row_layout.addWidget(restore_label)
        self.denoise_row_layout.addWidget(self.restore_type)
        self.denoise_row_layout.addStretch(1)
        layout.addRow(self.denoise_row_widget)
        # Hide restore label by default (only show if needed)
        restore_label.setVisible(False)
        self.restore_type.setVisible(False)

        # --- Fix vertical spacing jump by locking min height to max visible state ---
        def get_denoise_row_full_height():
            # Show all widgets to get the full height
            self.denoise_row_widget.show()
            restore_label.setVisible(True)
            self.restore_type.setVisible(True)
            self.denoise_row_widget.adjustSize()
            return self.denoise_row_widget.sizeHint().height()

        self._denoise_row_min_height = get_denoise_row_full_height()
        self.denoise_row_widget.setMinimumHeight(self._denoise_row_min_height)

        def update_denoise_restore_visibility():
            model = self.model_type.currentText()
            denoise_checked = self.do_denoise.isChecked()
            if model == "cpsam":
                self.denoise_row_widget.hide()
                self.pretrained_model_row_widget.hide()
            elif model in ("cyto2", "cyto3"):
                self.denoise_row_widget.show()
                self.pretrained_model_row_widget.hide()
                restore_label.setVisible(denoise_checked)
                self.restore_type.setVisible(denoise_checked)
            elif model == "custom":
                self.denoise_row_widget.hide()
                self.pretrained_model_row_widget.show()
            # Always keep min height so row doesn't collapse
            self.denoise_row_widget.setMinimumHeight(self._denoise_row_min_height)
        self.model_type.currentTextChanged.connect(update_denoise_restore_visibility)
        self.do_denoise.toggled.connect(update_denoise_restore_visibility)
        update_denoise_restore_visibility()
        self.diameter = QSpinBox()
        self.diameter.setRange(1, 200)
        self.diameter.setValue(40)
        diameter_label = QLabel("Diameter")
        diameter_label.setToolTip("Diameter for segmentation, e.g., 40 or 60. Defaults to 40. Deprecated in cellpose>=4.0, parameter will be ignored.")
        layout.addRow(diameter_label, self.diameter)
        # Flow Threshold
        self.flow_threshold = QDoubleSpinBox()
        self.flow_threshold.setRange(0, 10)
        self.flow_threshold.setValue(0.4)
        flow_label = QLabel("Flow Threshold")
        flow_label.setToolTip("Flow threshold for segmentation. Defaults to 0.4")
        layout.addRow(flow_label, self.flow_threshold)
        # Cellprob Threshold
        self.cellprob_threshold = QDoubleSpinBox()
        self.cellprob_threshold.setRange(-6, 6)
        self.cellprob_threshold.setValue(0)
        cellprob_label = QLabel("Cellprob Threshold")
        cellprob_label.setToolTip("Cell probability threshold for segmentation. Defaults to 0.")
        layout.addRow(cellprob_label, self.cellprob_threshold)
        # 3D Segmentation (move to advanced)
        self.do_3D = QCheckBox()
        self.do_3D.setChecked(False)
        do3d_label = QLabel("3D Segmentation")
        do3d_label.setToolTip("If True, will perform 3D segmentation. Defaults to False.")
        # Stitch Threshold 3D (move to advanced)
        self.stitch_threshold_3D = QDoubleSpinBox()
        self.stitch_threshold_3D.setRange(0, 1)
        self.stitch_threshold_3D.setValue(0)
        stitch3d_label = QLabel("Stitch Threshold 3D")
        stitch3d_label.setToolTip("Stitch threshold used for alternative 3D segmentation using IoU. `do_3D` needs to be False. Defaults to 0.")
        # Track Stitch Threshold
        self.track_stitch_threshold = QDoubleSpinBox()
        self.track_stitch_threshold.setRange(0, 1)
        self.track_stitch_threshold.setValue(0.75)
        trackstitch_label = QLabel("Track Stitch Threshold")
        trackstitch_label.setToolTip("Threshold for stitching masks during tracking. Defaults to 0.75.")
        layout.addRow(trackstitch_label, self.track_stitch_threshold)
    # Advanced settings box (hidden by default)
        self.advanced_box = QGroupBox()
        self.advanced_box.setTitle("")
        self.advanced_box.setVisible(False)
        adv_layout = QFormLayout(self.advanced_box)
        self.sigma = QDoubleSpinBox()
        self.sigma.setRange(0, 100)
        self.sigma.setValue(0)
        sigma_label = QLabel("Sigma")
        sigma_label.setToolTip("Sigma value for background subtraction. Defaults to 0.")
        adv_layout.addRow(sigma_label, self.sigma)
        self.size_spinbox = QSpinBox()
        self.size_spinbox.setRange(1, 100)
        self.size_spinbox.setValue(7)
        size_label = QLabel("Size")
        size_label.setToolTip("Size parameter for background subtraction. Defaults to 7.")
        adv_layout.addRow(size_label, self.size_spinbox)
        # GPU option
        self.gpu = QCheckBox()
        self.gpu.setChecked(True)
        gpu_label = QLabel("Use GPU")
        gpu_label.setToolTip("If checked, will use GPU for processing. Defaults to True.")
        adv_layout.addRow(gpu_label, self.gpu)
        adv_layout.addRow(do3d_label, self.do_3D)
        adv_layout.addRow(stitch3d_label, self.stitch_threshold_3D)

        self.advanced_btn = QPushButton("Show Advanced Settings")
        self.advanced_btn.setCheckable(True)
        def toggle_advanced():
            show = self.advanced_btn.isChecked()
            self.advanced_box.setVisible(show)
            self.advanced_btn.setText("Hide Advanced Settings" if show else "Show Advanced Settings")
        self.advanced_btn.clicked.connect(toggle_advanced)
        layout.addRow(self.advanced_btn)
        layout.addRow(self.advanced_box)
